### ISSUE TITLE
FK in tables during create process

### ISSUE THREAD

**Issue by paquitodev** [tom-gangemi/Force.com-Replicator#4]
I'm asking if it's possible to create FK between tables once them are created on the first time. I am using this DB and because large result sets queries sometimes takes a long because of `JOIN` or `UNION` sentences and because there is nothing indexed among tables, any advice on this one?

**Comment by tom-gangemi** [comment]
The Force.com-Replicator doesn't have the functionality to add or manage indexes and relationships in the DB. You can certainly add Indexes/Foreign Keys yourself without interfering with the operation of this tool.
