### ISSUE TITLE
Support for "multipicklist" field type

### ISSUE THREAD

**Issue by skwirrel** [tom-gangemi/Force.com-Replicator#5]
Data containing this field type causes the following error:
unsupported field type (multipicklist)

Fixing this just requires adding 
    case 'multipicklist':
on line 275 of Replicator.php thus...
    switch($field->type) {
                                        case 'id':
                                        case 'reference':
                                        case 'string':
                                        case 'picklist':
                                        case 'multipicklist':
                                        case 'textarea':
                                        case 'phone':
                                        case 'url':
                                        case 'url':

The data appears to be presented by SalesForce as a semicolon separated text field e.g.
Presenting;Jury
so handling this in the same way as picklist looks OK to me.

Just in case it helps here is a print_r of the $field object for a multipicklist field...

    [215] => stdClass Object
        (
            [autoNumber] =>
            [byteLength] => 4099
            [calculated] =>
            [caseSensitive] =>
            [createable] => 1
            [custom] => 1
            [defaultedOnCreate] =>
            [deprecatedAndHidden] =>
            [digits] => 0
            [filterable] => 1
            [groupable] =>
            [idLookup] =>
            [label] => Talent Support Interest
            [length] => 4099
            [name] => Talent_Support_Interest__c
            [nameField] =>
            [namePointing] =>
            [nillable] => 1
            [permissionable] => 1
            [picklistValues] => Array
                (
                    [0] => stdClass Object
                       (
                            [active] => 1
                            [defaultValue] =>
                            [label] => Presenting
                            [value] => Presenting
                        )

                    [1] => stdClass Object
                        (
                            [active] => 1
                            [defaultValue] =>
                            [label] => Hosting
                            [value] => Hosting
                        )

                    [2] => stdClass Object
                        (
                            [active] => 1
                            [defaultValue] =>
                            [label] => Mentoring
                            [value] => Mentoring
                        )

                    [3] => stdClass Object
                        (
                            [active] => 1
                            [defaultValue] =>
                            [label] => Events
                            [value] => Events
                        )

                    [4] => stdClass Object
                        (
                            [active] => 1
                            [defaultValue] =>
                            [label] => Jury
                            [value] => Jury
                        )

                )

            [precision] => 0
            [restrictedPicklist] =>
            [scale] => 0
            [soapType] => xsd:string
            [sortable] =>
            [type] => multipicklist
            [unique] =>
            [updateable] => 1
        )

)

**Comment by tom-gangemi** [comment]
I've made the change and pushed it into the repo.

Thanks for your help.
