### ISSUE TITLE
Support for >100 tables

### ISSUE THREAD

**Issue by skwirrel** [tom-gangemi/Force.com-Replicator#6]
Hi Tom,

Another small patch required to support backing up > 100 tables. There is a limit imposed by SF on the number of objects that can be included in a describe request (see https://developer.salesforce.com/forums/?id=906F00000008rHxIAI)

I have fixed this (snippet below) in the SynchSchema method. around line 194 or Replicator.php

Ben
=============================================================
                if(count($objectsToQuery) > 0) {

                        $objectUpserts = array();

                        // query object schemas from Salesforce
                        // SF only supports a maximum of 100 queries per call so we need to chunk this...
                        $describeBatchSize = @$this->config['objects'][$objectName]['options']['describeBatchSize'];
                        if (!$describeBatchSize) $describeBatchSize=100;
                        $describeBatches = array_chunk( array_keys($objectsToQuery), $describeBatchSize );
                        $describeResult = array();
                        foreach( $describeBatches as $describeBatch ) {
                                $describeBatchResult = $this->sf->getSObjectFields($describeBatch);
                                $describeResult = array_merge($describeResult,$describeBatchResult);
                        }

                        foreach ($describeResult as $objectName => $fields) {
=============================================================

**Comment by tom-gangemi** [comment]
I'll hopefully get to this soon but at a glance it doesn't look right.
You are using $objectName outside the context of iterating over each object - The setting is a wider context than each object too. 

I'm happy to submit it like this but feel free to make pull requests too.

Thank,
Tom
