### ISSUE TITLE
Save script output to file instead of see in console

### ISSUE THREAD

**Issue by paquitodev** [tom-gangemi/Force.com-Replicator#9]
I'm asking if there is any supported way to save the script output to a given file, if it's possible how? I want to keep a track on each script run to see what would be updated

Thanks in advance

PS: Since script is pretty easy I could add support for this feature request and then create a PR to integrate this, just let me know, I will start testing on my own

**Comment by tom-gangemi** [comment]
No need to modify the script. Just redirect the output like so:
`php Replicator.php >>file.txt 2>&1`
